name: "Terraform Plan"
on:
  workflow_call:
  push:
    paths:
      - '*/**'
  pull_request:
    branches: [ asdf ]

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash
jobs:
  terraform:
    name:   ${{matrix.runner}} - ${{ matrix.environment }}
    runs-on: [ '${{ matrix.runner }}']
    timeout-minutes: 15
    strategy:
      max-parallel: 1
      matrix:
         include:
           - environment: development
             runner: ubuntu-latest
           - environment: quality
             runner: ubuntu-18.04
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Format
        run: echo "Soon! :D" #terraform fmt -check

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::374632989470:role/GithubRole
          role-session-name: TerraformSession
          aws-region: us-east-1

      - name: Terraform Init
        id: init
        run: |
           rm -rf .terraform
           terraform init -backend-config=${{ matrix.environment }}/backend.tfvars -upgrade=true -no-color -input=false

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=${GITHUB_SHA}.plan -input=false -var-file=${{ matrix.environment }}/terraform.tfvars -no-color

      - name: 'Upload Terraform Plan'
          uses: actions/upload-artifact@v3
          with:
            name: ${GITHUB_SHA}
            path: ${GITHUB_SHA}.plan
            retention-days: 5