name: Terraform Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-pipeline:
    uses: crodcarocl/terraform-cloud/.github/workflows/ci.template.terraform.yml@main

  terraform-docs:
    needs: terraform-pipeline
    uses: crodcarocl/terraform-cloud/.github/workflows/ci.template.docs.yml@main
    with:
      resources-directory: "."