name: Terraform Pre-pullrequest

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  terraform-lint:
    uses: crodcarocl/terraform-cloud/.github/workflows/ci.template.checkov.yml@ft/testing
    with:
      resources-directory: "."