name: Generate terraform docs
on:
  pull_request:
    branches:
      - main
  workflow_call:
      inputs:
        resources-directory: # e.g. src/ecs-fargate/genetics TODO
          required: true
          type: string

jobs:
  terraform-docs:
    name: Terraform documentation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      # terraform-docs https://terraform-docs.io/how-to/github-action/
      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          output-file: ${{inputs.resources-directory}}/README.md # per module
          output-method: inject
          git-push: "true"