name: Terraform SSA

on:
  push:
    branches:
  workflow_call:
    inputs:
      resources-directory:
        default: "."
        description: 'Directory with infrastructure code and/or package manager files to scan'
        required: true
        type: string

jobs:
  checkov_analysis:
    name: Terraform Static Security Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{inputs.resources-directory}}
          framework: terraform