name: Terraform lambda

on:
  push:
    branches:
      - main
    paths:
      - '*/**'

jobs:
  terraform-lint:
    if: github.ref == 'refs/heads/ft/**' && github.event_name == 'push'
    uses: crodcarocl/terraform-cloud/.github/workflows/ci.template.checkov.yml@main
    with:
      resources-directory: development
  terraform-pipeline:
    needs: terraform-lint
    uses: crodcarocl/terraform-cloud/.github/workflows/ci.template.terraform.yml@main
    with:
      environment: development
  terraform-docs:
    needs: terraform-pipeline
    uses: crodcarocl/terraform-cloud/.github/workflows/ci.template.docs.yml@main
    with:
      resources-directory: development