name: Terraform lambda

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**/**'
  push:
    branches:
      - main
    paths:
      - '*/**'

jobs:
  terraform-lint:
    uses: crodcarocl/terraform-cloud/.github/workflows/ci.template.checkov.yml@main
    with:
      resources-directory: development
  terraform-docs:
    needs: terraform-lint
    uses: crodcarocl/terraform-cloud/.github/workflows/ci.template.docs.yml@main
    with:
      resources-directory: development