name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**/**'
  push:
    branches:
      - main
    paths:
      - '*/**'

jobs:
  unkwon:
    uses: crodcarocl/terraform-cloud/.github/workflows/ci.template.docs.yml@main
    with:
      resources-directory: development
  tflint:
    uses: crodcarocl/terraform-cloud/.github/workflows/ci.template.checkov.yml@main
    with:
      resources-directory: development