name: Terraform lambda

on:
  push:
    branches:
      - main
    paths:
      - '*/**'

jobs:
  terraform-lint:
    uses: crodcarocl/terraform-cloud/.github/workflows/ci.template.checkov.yml@main
    with:
      resources-directory: development
  terraform-init:
    needs: terraform-lint
    uses: crodcarocl/terraform-cloud/.github/workflows/ci.template.tfinit.yml@main
    with:
      resources-directory: development
  terraform-docs:
    needs: terraform-init
    uses: crodcarocl/terraform-cloud/.github/workflows/ci.template.docs.yml@main
    with:
      resources-directory: development