name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**/**'
  push:
    branches:
      - main
    paths:
      - '*/**'

jobs:
  tflint:
    if: ${{ github.event_name == 'pull_request' }}
    uses: terraform-cloud/.github/workflows/ci.template.checkov.yml@main